#Welcome to our Lab practice!

This lab is all about the package, Numpy. Are you ready? Let's go!

You will find some small tasks in sections below. 

> Try to figure out by yourself, or search for references. Being able to search and find information needed is an important skill that benefits you and your career for a long time.





## Import the package and rename it as np

In [2]:
import numpy as np

## Array Creation

### Task: Create a numpy array from a list of integers

In [4]:
a=np.array([0,1,2,3,4,5,6,7])
a


array([0, 1, 2, 3, 4, 5, 6, 7])

### Task: Create a numpy array of size 6, filled with zeros

In [7]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

###Task: Create a numpy array of size 6, filled with ones

In [9]:
np.ones(6,dtype=int)

array([1, 1, 1, 1, 1, 1])

###Task: Create a numpy array with values from 0 to 10

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

###Task: Create a numpy matrix of 2*3 integers, filled with zeros

In [11]:
np.zeros((2,3),dtype='int')

array([[0, 0, 0],
       [0, 0, 0]])

###Task: Create a numpy matrix of 3*2 integers, filled with ones

In [ ]:
np.ones((3,2),dtype='int')

###Task: Create a numpy matrix of 3*2 integers, filled with random integers in [0, 10]

In [14]:
import random
np.random.randint(0,10,(3,2))

array([[6, 6],
       [0, 2],
       [4, 6]])

###Task: Create a numpy matrix of 100 * 2, filled with random float value in [0, 1]

In [15]:
import random
np.random.rand(0,1,(100*2))

array([], shape=(0, 1, 200), dtype=float64)

###Task: Create a numpy matrix of 2 * 3 * 4, filled with integers from 1 to 24.

In [16]:
import random
np.random.randint(1,24,(2,3,4))

array([[[10, 11,  5, 20],
        [12, 17, 10,  6],
        [ 4, 10, 21, 11]],

       [[19,  8, 11,  4],
        [18, 15,  1,  8],
        [ 5, 17,  8, 13]]])

## Array Indexing

### Task: Let X be a numpy array, and X = np.array([1, 2, 3, 4, 5])

In [18]:
X=np.array([1,2,3,4,5])
X

array([1, 2, 3, 4, 5])

### Task: Show the first element of X

In [22]:
X[0]

1

### Task: Show the last element of X

In [23]:
X[-1]

5

### Task: Show the first 3 elements of X

In [25]:
X[:3]

array([1, 2, 3])

###Task: Show the last 3 elements of X

In [28]:
X[2:]

array([3, 4, 5])

###Task: Show the elements of X whose index is odd (1, 3, 5, ...)

In [30]:
X[0::2]

array([1, 3, 5])

###Task: Show the elements of X except the last one

In [31]:
X[0:4]

array([1, 2, 3, 4])

### Task: Let X be a numpy matrix with dimension 3 * 4, and filled from 0 to 11.

In [34]:
X=np.random.randint(0,11,(3,4))
X

array([[ 4,  9,  8,  5],
       [ 9, 10, 10,  9],
       [ 2,  2,  6,  9]])

###Task: Show the first row of X

In [35]:
X[0]

array([4, 9, 8, 5])

###Task: Show the first column of X

In [37]:
X[:,0]

array([4, 9, 2])

###Task: Show the first element of the first row of X

In [38]:
X[0,0]

4

###Task: Show the last row of X

In [40]:
X[2]

array([2, 2, 6, 9])

###Task: Show the last column of X

In [42]:
X[:,3]

array([5, 9, 9])

###Task: Show the last element of the last row of X

In [44]:
X[2,3]

9

###Task: Show all the rows except the last row of X

In [48]:
X[:-1, :]

array([[ 4,  9,  8,  5],
       [ 9, 10, 10,  9]])

###Task: Show all the columns except the last column of X

In [54]:
X[: ,:-1]

array([[ 4,  9,  8],
       [ 9, 10, 10],
       [ 2,  2,  6]])

### Task: Show the first two elements of the first two rows

In [70]:
X[:2,:2]

array([[ 4,  9],
       [ 9, 10]])

## Array Statistics

###Task: Create a numpy array X, print the sum, mean, std, var, max, min of it

In [77]:
X=np.arange(100)
print(X.sum())
print(X.mean())
print(X.std())
print(X.max())
print(X.var())
print(X.min())


4950
49.5
28.86607004772212
99
833.25
0


###Task: Create a numpy matrix X as n * m, print the sum, mean, std, var, max, min of the 1st row of it.

In [80]:
r1=X[0]
print(r1.sum())
print(r1.mean())
print(r1.std())
print(r1.max())
print(r1.var())
print(r1.min())

25
8.333333333333334
1.699673171197595
10
2.8888888888888893
6


###Task: Create a numpy matrix X as n * m, print the sum, mean, std, var, max, min of the 1st column of it.

In [81]:
r1=X[:,0]
print(r1.sum())
print(r1.mean())
print(r1.std())
print(r1.max())
print(r1.var())
print(r1.min())

19
9.5
0.5
10
0.25
9


## Array Linear Algebra

###Task: Create two numpy matrix X with 2 * 2, and Y with 2 * 2. Practice Linear Algebra operations, such as +, -, *, .T, @, etc. 

In [83]:
X=np.random.randint(0,10,(2,2))
Y=np.random.randint(11,20,(2,2))
print(X+Y)
print(X-Y)
print(X*Y)
print(X.T)
print(Y.T)
print(X@Y.T)
print(Y@X.T)

[[20 15]
 [19 19]]
[[-10  -9]
 [-17 -19]]
[[75 36]
 [18  0]]
[[5 1]
 [3 0]]
[[15 18]
 [12 19]]
[[111 147]
 [ 15  18]]
[[111  15]
 [147  18]]
